dup 20 countdown-step
dup 19 countdown-step
dup 18 countdown-step
dup 17 countdown-step
dup 16 countdown-step
dup 15 countdown-step
dup 14 countdown-step
dup 13 countdown-step
dup 12 countdown-step
dup 11 countdown-step
dup 10 countdown-step
dup 9 countdown-step
dup 8 countdown-step
dup 7 countdown-step
dup 6 countdown-step
dup 5 countdown-step
dup 4 countdown-step
dup 3 countdown-step
dup 2 countdown-step
dup 1 countdown-step
drop countdown-thanks
