dup 99 countdown-step
dup 98 countdown-step
dup 97 countdown-step
dup 96 countdown-step
dup 95 countdown-step
dup 94 countdown-step
dup 93 countdown-step
dup 92 countdown-step
dup 91 countdown-step
dup 90 countdown-step
dup 89 countdown-step
dup 88 countdown-step
dup 87 countdown-step
dup 86 countdown-step
dup 85 countdown-step
dup 84 countdown-step
dup 83 countdown-step
dup 82 countdown-step
dup 81 countdown-step
dup 80 countdown-step
dup 79 countdown-step
dup 78 countdown-step
dup 77 countdown-step
dup 76 countdown-step
dup 75 countdown-step
dup 74 countdown-step
dup 73 countdown-step
dup 72 countdown-step
dup 71 countdown-step
dup 70 countdown-step
dup 69 countdown-step
dup 68 countdown-step
dup 67 countdown-step
dup 66 countdown-step
dup 65 countdown-step
dup 64 countdown-step
dup 63 countdown-step
dup 62 countdown-step
dup 61 countdown-step
dup 60 countdown-step
dup 59 countdown-step
dup 58 countdown-step
dup 57 countdown-step
dup 56 countdown-step
dup 55 countdown-step
dup 54 countdown-step
dup 53 countdown-step
dup 52 countdown-step
dup 51 countdown-step
dup 50 countdown-step
dup 49 countdown-step
dup 48 countdown-step
dup 47 countdown-step
dup 46 countdown-step
dup 45 countdown-step
dup 44 countdown-step
dup 43 countdown-step
dup 42 countdown-step
dup 41 countdown-step
dup 40 countdown-step
dup 39 countdown-step
dup 38 countdown-step
dup 37 countdown-step
dup 36 countdown-step
dup 35 countdown-step
dup 34 countdown-step
dup 33 countdown-step
dup 32 countdown-step
dup 31 countdown-step
dup 30 countdown-step
dup 29 countdown-step
dup 28 countdown-step
dup 27 countdown-step
dup 26 countdown-step
dup 25 countdown-step
dup 24 countdown-step
dup 23 countdown-step
dup 22 countdown-step
dup 21 countdown-step
dup 20 countdown-step
dup 19 countdown-step
dup 18 countdown-step
dup 17 countdown-step
dup 16 countdown-step
dup 15 countdown-step
dup 14 countdown-step
dup 13 countdown-step
dup 12 countdown-step
dup 11 countdown-step
dup 10 countdown-step
dup 9 countdown-step
dup 8 countdown-step
dup 7 countdown-step
dup 6 countdown-step
dup 5 countdown-step
dup 4 countdown-step
dup 3 countdown-step
dup 2 countdown-step
dup 1 countdown-step
drop countdown-thanks
